### PR TITLE
Gametest beta 1.20.50

### PR DESCRIPTION
**Pull request by MrDiamond64**

### CODE REVIEW

**Comment by NuttyGta** [comment]
I have a problem with the anti cheat version minecraft 1.20.50 does not work. a server provider has to have a version higher 1.20.53 so it might work. to play on my world I like using your anti cheat. I don't know if it's possible if you could include hiya number versions

**Comment by MrDiamond64** [comment]
> I have a problem with the anti cheat version minecraft 1.20.50 does not work. a server provider has to have a version higher 1.20.53 so it might work. to play on my world I like using your anti cheat. I don't know if it's possible if you could include hiya number versions

What version of Scythe are you using? You can check by running the `/function version` command.

**Comment by NuttyGta** [comment]
the old version was disabled 1.20.40 the new version does not want to work 1.20.50

**Comment by NuttyGta** [comment]
hi can you me  Scythe AntiCheat minecraft bedrock anticheat is not working servers ERROR] Unknown command: Scythe-Anticheat. Please check that the command exists and that you have permission to use it.version out of data

**Comment by MrDiamond64** [comment]
> hi can you me Scythe AntiCheat minecraft bedrock anticheat is not working servers ERROR] Unknown command: Scythe-Anticheat. Please check that the command exists and that you have permission to use it.version out of data

That is because you are trying to run a command named "Scythe-Anticheat". That is not how you use Scythe.

**Comment by NuttyGta** [comment]
how do I correct it then

**Pull request merged**
